content:
  - name: "series"
    label: "ุงููุณูุณูุงุช ูุงูุฃููู"
    filename: "src/content/series/[name].json" # ุงุณู ุงูููู ุณูููู ุญุณุจ ุงูุนููุงู
    type: collection # ุฃู type: file ุฅุฐุง ููุช ุชุณุชุฎุฏู ููู ูุงุญุฏ ูููู
    path: "src/content/series" # ูุฌูุฏ ุงููุญุชูู

    fields:
      # ุญููู ูุณุชูู ุงููุณูุณู/ุงูุฃููู
      - { name: "title", label: "ุนููุงู ุงูุณูุณูุฉ", type: string }
      - { name: "slug", label: "ุงูุฑุงุจุท (Slug)", type: string }
      - { name: "description", label: "ุงููุตู", type: text }

      # ----------------------------------------------------------------
      # 1. ูุงุฆูุฉ ุงูููุงุณู (Nested Array)
      # ูุณุชุฎุฏู 'type: object' ูุน ุญููู ุฏุงุฎููุฉุ ููุนุชูุฏ ุนูู Pages CMS 
      # ูููู ุฃู ูุฐุง ุงูุญูู ููุซู ูุตูููุฉ ูุงุจูุฉ ููุชูุฑุงุฑ (Repeatable List).
      # ูุฏ ูุญุชุงุฌ ุฅูู ุฅุถุงูุฉ ุฎุงุตูุฉ ูุซู 'list: true' ุฃู 'repeated: true' 
      # ุฅุฐุง ูู ููู ุงููุธุงู ูุชุนุฑู ุนูููุง ุชููุงุฆูุงู.

      - name: "genres"
        label: "ุชุตููู ุงูุฃููู"
        type: select
        multiple: true # ๐ก ุฌุฑุจ ูุฐู ุงูุฎุงุตูุฉ ููุณูุงุญ ุจุงุฎุชูุงุฑ ุฃูุซุฑ ูู ุนูุตุฑ
        options:
          values:
            - { value: "action", label: "ุฃูุดู" }
            - { value: "comedy", label: "ููููุฏูุง" }
            - { value: "romance", label: "ุฑููุงูุณู" }
            - { value: "scifi", label: "ุฎูุงู ุนููู" }
      
      - name: "seasons"
        label: "ุงูููุงุณู"
        type: object # ูุชูุซูู ูุงุฆู ุงูููุณู
        list: true
        # ๐ก ููุงุญุธุฉ: ูุฌุจ ุฃู ุชุถูู ุฎุงุตูุฉ ุชุฌุนู ูุฐุง ุงููุงุฆู ูุงุจู ููุชูุฑุงุฑ
        #  (ุนูู ุณุจูู ุงููุซุงูุ list: true ุฃู max: 0).
        #  ุณููุชุฑุถ ุฃู Pages CMS ูุชุทูุจ ููู ุจุจุณุงุทุฉ ุชุนุฑูู ุงูุญููู ุฏุงุฎูู.
        
        fields:
          - { name: "season_number", label: "ุฑูู ุงูููุณู", type: number }
          - { name: "season_title", label: "ุนููุงู ุงูููุณู", type: string }
          
          # ------------------------------------------------------------
          # 2. ูุงุฆูุฉ ุงูุญููุงุช (Nested Array ุฏุงุฎู ุงูููุณู)
          - name: "episodes"
            label: "ุงูุญููุงุช"
            type: object # ูุชูุซูู ูุงุฆู ุงูุญููุฉ
            list: true
            # ๐ก ููุง ุฃูุถุงู ูุญุชุงุฌ ุฎุงุตูุฉ ุงููุงุฆูุฉ/ุงูุชูุฑุงุฑ (ูุซู list: true)
            
            fields:
              - { name: "episode_number", label: "ุฑูู ุงูุญููุฉ", type: number }
              - { name: "episode_title", label: "ุนููุงู ุงูุญููุฉ", type: string }
              - { name: "video_url", label: "ุฑุงุจุท ุงูููุฏูู", type: string }
              - { name: "duration", label: "ูุฏุฉ ุงูุญููุฉ", type: string }