collections:
  - name: series
    label: ุงููุณูุณูุงุช ูุงูุฃููู
    # ููุงุ type: collection ูุชู ุชุนุฑููู ูู ุณูุงู ุฃุนูู (ุชุญุช collections)
    path: src/content/series
    format: json
    
    # ๐ ููุง ูุฌุจ ุฃู ุชุจุฏุฃ ุจุชุนุฑูู ุญููู ุงูุจูุงูุงุช ุงููุนููุฉ ๐
    schema: # ๐ก ูุฏ ูููู ูุฐุง ูู ุงูููุงู ุงูุตุญูุญ ูุชุนุฑูู ุงูุญููู
      fields:
        - name: title
          label: ุนููุงู ุงูุณูุณูุฉ
          type: string # โ ุงูุขู ููููู ุงุณุชุฎุฏุงู ุงูุฃููุงุน ุงูุฃุณุงุณูุฉ
        - name: slug
          label: ุงูุฑุงุจุท (Slug)
          type: string

        # ----------------------------------------------------
        # 1. ูุงุฆูุฉ ุงูููุงุณู: ููุน ุงูุญูู ุงูุขู ูู 'array' (ุฃู 'list') 
        - name: seasons
          label: ุงูููุงุณู
          type: array # ๐ก ุชุฌุฑุจุฉ array ูุฌุฏุฏูุง ูู ูุฐุง ุงููุณุชูู
          items: # ๐ก ุชุฌุฑุจุฉ items ูุฌุฏุฏูุง ูู ูุฐุง ุงููุณุชูู
            type: object # ูู ุนูุตุฑ ูู ุงููุงุฆูุฉ ูู ูุงุฆู (ููุณู)
            fields:
              - name: season_number
                label: ุฑูู ุงูููุณู
                type: number
              
              # 2. ูุงุฆูุฉ ุงูุญููุงุช ุงููุชุฏุงุฎูุฉ
              - name: episodes
                label: ุงูุญููุงุช
                type: array
                items:
                  type: object
                  fields:
                    - name: episode_number
                      label: ุฑูู ุงูุญููุฉ
                      type: number
                    - name: title
                      label: ุนููุงู ุงูุญููุฉ
                      type: string