collect:
  - name: series
    label: ุงููุณูุณูุงุช ูุงูุฃููู
    path: src/content/series
    format: json
    fields:
      - name: title
        label: ุนููุงู ุงูุณูุณูุฉ
        type: string
      - name: slug
        label: ุงูุฑุงุจุท (Slug)
        type: string

      # ----------------------------------------------------
      # 1. ูุงุฆูุฉ ุงูููุงุณู (ุงููุฌููุนุฉ ุงูุฎุงุฑุฌูุฉ)
      - name: seasons
        label: ุงูููุงุณู
        type: collection # ๐ก ูุญุงููุฉ ุงุณุชุฎุฏุงู 'collection' ุจุฏูุงู ูู 'array' ุฃู 'list'
        fields: # ๐ก ูุญุงููุฉ ุงุณุชุฎุฏุงู 'fields' ุจุฏูุงู ูู 'items'
          - name: season_number
            label: ุฑูู ุงูููุณู
            type: number
          - name: title
            label: ุนููุงู ุงูููุณู
            type: string

          # ------------------------------------------------
          # 2. ูุงุฆูุฉ ุงูุญููุงุช (ุงููุฌููุนุฉ ุงูุฏุงุฎููุฉ)
          - name: episodes
            label: ุงูุญููุงุช
            type: collection # ๐ก ุงุณุชุฎุฏุงู 'collection' ูุชูุซูู ูุงุฆูุฉ ุงูุญููุงุช
            fields:
              - name: episode_number
                label: ุฑูู ุงูุญููุฉ
                type: number
              - name: title
                label: ุนููุงู ุงูุญููุฉ
                type: string
              - name: video_url
                label: ุฑุงุจุท ุงูููุฏูู
                type: string